slam_toolbox:
  ros__parameters:
    mode: 'mapping'
    use_sim_time: false
    base_frame: 'f1tenth_1'
    odom_frame: 'f1tenth_1_odom'
    map_frame: 'map'
    throttle_scans: 2
    scan_queue_size: 50
    save_map_path: '/home/autroboracer/ros2_ws/src/roboracer-autodrive/localization/maps' 
